spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: debug